### ISSUE TITLE
Update URL in README.md

### ISSUE THREAD

**Issue by ghost** [zeit-ui/typography#8]
## Description

The URL in [Example Site](https://github.com/geist-org/typography#example) is broken.

- [x] I can create a Pull Request on confirmation.

## Current Behavior

[Link](https://typography.geist-ui.co/) `https://typography.geist-ui.co/`

## Expected

[Link](https://typography.geist-ui.dev/) `https://typography.geist-ui.dev/`

**Comment by unix** [comment]
❤️ Thanks for your proposal, you can create a pull-request at any time.
